Finished
GayaHealth/Gaya_Website pull request #44
Opened 2023-07-07 20:12 UTC by shenghungKuan

close #40 
<img width="271" alt="截圖 2023-07-07 下午1 06 49" src="https://github.com/GayaHealth/Gaya_Website/assets/111332833/4f1e35b4-54f0-4c6e-93e1-c6548e21d378">

2023-07-07 22:24 UTC, lawrenceslng commented on client/src/components/About/Banner.js
> +const styles = {
this is not necessary, nothing in the file uses `styles` or `gridContainer`

2023-07-07 22:26 UTC, lawrenceslng requested changes
recommend making the changes mentioned

2023-07-07 22:26 UTC, lawrenceslng commented on client/src/components/About/Banner.js
I recommend moving this file to 1 level above since this is used in 2 pages

2023-07-07 22:26 UTC, lawrenceslng commented on client/src/components/About/Mission.js
> +            <h2 style={{color: "#802A4F", fontSize: '20px'}}>
I recommend looking at the `Typography` tag in Material UI and not use h1 and h2 unless they are actually headers

2023-07-07 22:26 UTC, lawrenceslng commented on client/src/components/About/Strategy1.js
> +const styles = {
same comment as before

2023-07-07 22:26 UTC, lawrenceslng commented on client/src/components/About/Strategy1.js
> +            <h2 style={{color: "#802A4F", fontSize: '20px'}}>
same h1 h2 comment as before

2023-07-07 22:26 UTC, lawrenceslng commented on client/src/components/About/Strategy2.js
same comments as before

2023-07-08 18:01 UTC, shenghungKuan commented on client/src/components/About/Banner.js
Should I change its file name? Or just banner is fine

2023-07-09 05:11 UTC, lawrenceslng approved these changes
looks good, ready to merge

2023-07-09 05:12 UTC, lawrenceslng commented on client/src/components/About/Banner.js
as long as there is no conflict and it's clear which is used where, the naming is up to you

2023-07-09 17:26 UTC, merged