Shenghung kuan 43 create theme for app
GayaHealth/Gaya_Website pull request #73
Opened 2023-07-17 21:02 UTC by shenghungKuan

Since things changed, I'm thinking of merging the theme.js first and then creating another issue to apply the theme to all the components
close #43

2023-07-18 16:59 UTC, lawrenceslng requested changes
I think the code looks pretty good, I think you can open an issue for the following 2 recommendations and we can come back to it when we have time:

1) there are still some mobile responsiveness code in some files, would be nice to consolidate within `Theme.js`
2) there are still some stylings for things like margins and stuff that could be consolidated too

Can you pull latest dev branch and merge with your branch and update the PR? Then I'll run your branch and check if there's any styling that we should fix

2023-07-18 18:05 UTC, shenghungKuan commented
Since some of them have different responsive sizes and margins, I just left it as what it is.
If we want to consolidate all of them, I may need your opinions or to discuss which one to apply.
And yes, I'll merge the dev into this branch first.

2023-07-20 00:07 UTC, lawrenceslng requested changes
Just 1 little change

2023-07-20 00:07 UTC, lawrenceslng commented on client/src/components/Root/Banner.js
we need to add a little more margins between the three parts within the Banner and the 2nd part needs a heavier font weight:

latest:
<img width="1100" alt="image" src="https://github.com/GayaHealth/Gaya_Website/assets/38678774/fd5295b6-df75-4d83-aa5a-d381d048afd0">


Wireframe:
<img width="786" alt="image" src="https://github.com/GayaHealth/Gaya_Website/assets/38678774/6b2e211d-a928-4042-aaee-71e5a888b9a6">

2023-07-20 16:56 UTC, shenghungKuan commented on client/src/components/Root/Banner.js
Good catch!!!

2023-07-20 19:39 UTC, shenghungKuan commented on client/src/components/Root/Banner.js
<img width="737" alt="截圖 2023-07-20 下午12 38 32" src="https://github.com/GayaHealth/Gaya_Website/assets/111332833/8162e8b0-dec8-4234-8e3f-f027163762c6">
<img width="653" alt="截圖 2023-07-20 下午12 38 39" src="https://github.com/GayaHealth/Gaya_Website/assets/111332833/294a604c-e17e-4f5d-8bb5-898c6f2970fa">

2023-07-21 17:55 UTC, shenghungKuan commented on client/src/components/Root/Banner.js
@lawrenceslng @zhunan123 please take a look and approve if it looks good to you. Thanks.

2023-07-21 22:22 UTC, lawrenceslng approved these changes
Approved

2023-07-21 22:33 UTC, merged